### ISSUE TITLE
Remove bundle install as prereq for release workflow

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-requirements#12]
I am trying to remove a circular dependency of isodoc on isodoc-i18n:

isodoc depends on mn-requirements
mn-requirements depends on isodoc-i18n
isodoc depends on isodoc-i18n
mn-requirements depends on isodoc (development only)

I am removing the dependency of isodoc on isodoc-i18n tomorrow, and I'm trying to release mn-requirements today; but bundle install + the development dependency on mn-requirements are preventing me from running release. 

I understand that we are releasing bundle install from all release tasks, in order to deal with this kind of circularity?

**Comment by CAMOBAP** [comment]
@opoudjis this is our current release workflow https://github.com/metanorma/ci/blob/main/.github/workflows/rubygems-release.yml

I easily can remove `bundler-cache: true` from it and it will be applied to most our repos

The question is will `bundle exec rake release` command work without prior `bundle install`?

Or should we install `rake` with `gem install rake`?

**Comment by CAMOBAP** [comment]
Done

Per discussion with @opoudjis rake is a preinstalled gem so it safe to remove `bundle install`
