### ISSUE TITLE
Consistency in rendering "Dependency" and "Provisions"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-requirements#15]
In a requirements class "Provisions" contain multiple provisions.
<img width="863" alt="Screen Shot 2022-10-06 at 12 43 51 AM" src="https://user-images.githubusercontent.com/11865/194115717-a8cf3513-fe1d-4f86-ad20-4138665e361e.png">

However, in a requirement, "Dependency" is each shown on individual rows.
<img width="866" alt="Screen Shot 2022-10-06 at 12 43 36 AM" src="https://user-images.githubusercontent.com/11865/194115658-14baede4-2ed8-48c7-b913-4f68dd3c7f09.png">

Can we apply the same treatment across both, i.e. if there are multiple, keep them together?

**Comment by opoudjis** [comment]
Label currently is singular. Will implement inflection lookup method (which we have not had to do until now), so we can supply optional plural.

**Comment by opoudjis** [comment]
Allowing the following headings to be pluralised:

Provision, Conformance Test, Statement, Dependency, Indirect Dependency

**Comment by ronaldtse** [comment]
@opoudjis 
"Dependency" => "Prerequisite"
"Indirect Dependency" => "Indirect prerequisites"

**Comment by ronaldtse** [comment]
Please generalize this for OGC as well, thanks.

**Comment by ronaldtse** [comment]
Confirmed in ISO 19115-3.

"Provisions:"
<img width="659" alt="Screen Shot 2022-10-18 at 11 06 30 PM" src="https://user-images.githubusercontent.com/11865/196469398-639dbe0d-9628-44bb-bae7-607866f2fc83.png">

"Conformance tests:" and "Prerequisites:"
<img width="660" alt="Screen Shot 2022-10-18 at 11 06 01 PM" src="https://user-images.githubusercontent.com/11865/196469254-acded1e5-ead7-4ba1-8271-d8b7f03c7915.png">

This document does not have "Indirect prerequisites" so can't check.
