### ISSUE TITLE
Render with left table column as header column

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-requirements#19]
As suggested by the ISO/TC 211 EPM, the table headings in the left column can be rendered in bold for clarity.

**Comment by opoudjis** [comment]
In ISO or in general? @ronaldtse

**Comment by opoudjis** [comment]
Not yet merged.

**Comment by ronaldtse** [comment]
Confirmed to be fixed. Thanks @opoudjis !
<img width="649" alt="Screen Shot 2022-10-19 at 12 07 51 AM" src="https://user-images.githubusercontent.com/11865/196484516-24f30a1d-09c0-4e28-9943-8cf1bd32ca41.png">
