### ISSUE TITLE
rubygems publishing by tagging?

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-requirements#5]
I've started using tags instead of rake release to push out versions of gems. I've manually pushed mn-requirements to rubygems, since neither 0.0.3 nor 0.1.0 was pushed (the former 5 days ago). Could I confirm that tagging is set up to publish mn-requirements ?

**Comment by ronaldtse** [comment]
For starters, you need to run these commands to grant publication privileges.

```
gem owner mn-requirements -a ribose
gem owner mn-requirements -a metanorma
```

**Comment by CAMOBAP** [comment]
Because we use general workflow for many repositories, some of them require access to GH rubygems.
@ronaldtse could you please confirm that this repo has access to both:
 - secrets.METANORMA_CI_RUBYGEMS_API_KEY
 - secrets.METANORMA_CI_PAT_TOKEN

*both are org-level secrets as far as I remember

**Comment by ronaldtse** [comment]
@CAMOBAP yes they are both available here, it is only with private repos we have to manually set. The issue is that @opoudjis needs to add the CI user as gen owner.

**Comment by opoudjis** [comment]
Done.

**Comment by ronaldtse** [comment]
Confirm done.

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis  should we rerun latest failed release workflow?

**Comment by opoudjis** [comment]
Btw, Github Actions is going to fail for all of mn-requirements, metanorma-standoc and isodoc, because of circular dependencies: they all need to be upgraded together.

**Comment by CAMOBAP** [comment]
@opoudjis https://github.com/metanorma/metanorma-standoc/tree/main/.github/workflows doesn't have automatic release workflow as many other gems, I tried to add release workflow to only independent components

Anyway let me know if there is make sense to add/remove automatic release workflow for some repos

**Comment by CAMOBAP** [comment]
> @CAMOBAP we want automatic release for all gems in the metanorma, relaton orgs. Thanks!

Ok

cc @andrew2net to be on the same page. AFAIK you are probably working on relaton projects more than others

> Btw, Github Actions is going to fail for all of mn-requirements, metanorma-standoc and isodoc, because of circular dependencies: they all need to be upgraded together.

This "circle" comes from development deps, to me it looks like order should be:

**Comment by CAMOBAP** [comment]
@ronaldtse could you please confirm that `RELATON_CI_RUBYGEMS_API_KEY` or similar is available for `relaton` org?

**Comment by opoudjis** [comment]
https://github.com/metanorma/isodoc-i18n/issues/4 Attention @CAMOBAP

**Comment by CAMOBAP** [comment]
CI configuration updated for all rmetanorma and relaton epos

**Comment by andrew2net** [comment]
@CAMOBAP I've tried to make tag and push it to relaton-bipm repo but nothing happened.
```
error parsing called workflow "relaton/support/.github/workflows/release.yml@master": failed to fetch workflow: workflow was not found.
```
https://github.com/relaton/relaton-bipm/actions/runs/3028659644

**Comment by CAMOBAP** [comment]
@andrew2net my bad forgot to push `relaton/support` could you please try one more time

**Comment by andrew2net** [comment]
@CAMOBAP I've already released the relaton-bipm using `rake release` command. Will try next time.

**Comment by andrew2net** [comment]
@CAMOBAP what is correct workflow to release gem?
I make a commit, then I push the commit and wait until all GHA tests completed, then create a tag and push it.
Then I push tag the GHA tests run again. I think we don't need it.

**Comment by CAMOBAP** [comment]
> Then I push tag the GHA tests run again. I think we don't need it.

Agree, we have workaround for this on metanorma gems, I will implement the same approach for relaton gems

**Comment by CAMOBAP** [comment]
@andrew2net done
